### ISSUE TITLE
Re-Implement ChatMessage deserialization

### ISSUE THREAD

**Issue by Tides** [Naamloos/Obsidian#448]
With the new 1.21 update, Mojang decided to switch from JSON to NBT for chat de/serialization. Fixing it might be a little tedious since we don't have a serializer built for NBT but should still be an easy task to do. 

[MinecraftStream.Reading.cs:L538](https://github.com/ObsidianMC/Obsidian/blob/1.21.x/Obsidian/Net/MinecraftStream.Reading.cs#L538)

If you wanna know what properties that you're looking to read, you can check out [this](https://github.com/ObsidianMC/Obsidian/blob/1.21.x/Obsidian/Net/MinecraftStream.Writing.cs#L427-L468) or [ChatMessage.cs](https://github.com/ObsidianMC/Obsidian/blob/1.21.x/Obsidian.API/_Types/ChatMessage.cs)

**Comment by Craftplacer** [comment]
they what
